version: '2'
services:
  runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
      - config:/etc/gitlab-runner:Z

volumes:
  config:
    driver: local
